"""Upgrade tasks table

Revision ID: d31774760a9c
Revises: 0d99f9f6697a
Create Date: 2025-05-14 20:25:07.326752

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d31774760a9c"
down_revision: Union[str, None] = "0d99f9f6697a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tasks", "assignee_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tasks", "assignee_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
